CREATE TABLE IF NOT EXISTS mpa_rating (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE IF NOT EXISTS users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar,
  login varchar,
  name varchar,
  birthday date
);

CREATE TABLE IF NOT EXISTS films (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar(200),
  release_date date,
  duration int,
  mpa_id int REFERENCES mpa_rating (id)
);

CREATE TABLE IF NOT EXISTS genres (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE IF NOT EXISTS friends (
  user_id int REFERENCES users (id),
  friend_id int REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id int REFERENCES films (id),
  genre_id int REFERENCES genres (id)
);

CREATE TABLE IF NOT EXISTS film_likes (
  film_id int REFERENCES films (id),
  user_id int REFERENCES users (id)
);
