CREATE TABLE IF NOT EXISTS mpa_rating (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255)
);

CREATE TABLE IF NOT EXISTS users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL,
  login varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(200) NOT NULL,
  release_date date NOT NULL,
  duration int CHECK (duration > 0),
  mpa_id int REFERENCES mpa_rating (id)
);

CREATE TABLE IF NOT EXISTS genres (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255)
);

CREATE TABLE IF NOT EXISTS friends (
  user_id int REFERENCES users (id),
  friend_id int REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id int REFERENCES films (id),
  genre_id int REFERENCES genres (id)
);

CREATE TABLE IF NOT EXISTS film_likes (
  film_id int REFERENCES films (id),
  user_id int REFERENCES users (id)
);
